In [1]:
import pandas as pd

In [2]:
#list
l = [9,8,7,6,5,4,3,2,1]

In [3]:
type(l)

list

In [4]:
l

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [5]:
#list to series making
s1 = pd.Series(l)

In [6]:
print(s1)

0    9
1    8
2    7
3    6
4    5
5    4
6    3
7    2
8    1
dtype: int64

In [7]:
type(s1)

pandas.core.series.Series

In [8]:
#series to dataframe making
df1 = pd.DataFrame(s1,columns = ['Num'])

In [9]:
type(df1)

pandas.core.frame.DataFrame

In [10]:
df1

   Num
0    9
1    8
2    7
3    6
4    5
5    4
6    3
7    2
8    1

In [11]:
#list to dataframe making
df2 = pd.DataFrame(l,columns = ['Num'])

In [12]:
df2

   Num
0    9
1    8
2    7
3    6
4    5
5    4
6    3
7    2
8    1

In [13]:
#dataframe to series
s2 = df2['Num']

In [14]:
s2

0    9
1    8
2    7
3    6
4    5
5    4
6    3
7    2
8    1
Name: Num, dtype: int64

In [15]:
type(s2)

pandas.core.series.Series

In [16]:
#making list with multiple column
li = [[1,2,3],
      [4,5,6],
      [7,8,9]]

In [17]:
li

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
#list(with multiple column) to dataframe making
df3 = pd.DataFrame(li,columns = ['Num1','Num2','Num3'])

In [19]:
df3

   Num1  Num2  Num3
0     1     2     3
1     4     5     6
2     7     8     9

In [20]:
#dataframe (with multiple column) to series
s3 = df3[['Num1','Num2']]
s3

   Num1  Num2
0     1     2
1     4     5
2     7     8

In [21]:
s4 = df3['Num3']
s4

0    3
1    6
2    9
Name: Num3, dtype: int64

In [22]:
type(s3)

pandas.core.frame.DataFrame

In [23]:
type(s4)

pandas.core.series.Series