In [1]:
import pandas as pd

In [2]:
#making a set
s = {1,2,3,4,5,2,1}

In [3]:
s

{1, 2, 3, 4, 5}

In [4]:
type(s)

set

In [5]:
#making a series from set
se1 = pd.Series(list(s),name = 'INT')

In [6]:
se1

0    1
1    2
2    3
3    4
4    5
Name: INT, dtype: int64

In [7]:
type(se1)

pandas.core.series.Series

In [8]:
#making a dataframe from set.
data = pd.DataFrame(s,columns = ['Value'])

In [9]:
data

   Value
0      1
1      2
2      3
3      4
4      5

In [10]:
type(data)

pandas.core.frame.DataFrame

In [11]:
#making a tuple
t = (1,2,3,4,5.5,6.7,True,False,'Kohin','Saydad')

In [12]:
t

(1, 2, 3, 4, 5.5, 6.7, True, False, 'Kohin', 'Saydad')

In [13]:
type(t)

tuple

In [14]:
#making series from tuple
se2 = pd.Series(t)

In [15]:
se2

0         1
1         2
2         3
3         4
4       5.5
5       6.7
6      True
7     False
8     Kohin
9    Saydad
dtype: object

In [16]:
type(se2)

pandas.core.series.Series

In [17]:
#making dataframe from tuple
data2 = pd.DataFrame(t,columns = ['Objcets'])

In [18]:
data2

  Objcets
0       1
1       2
2       3
3       4
4     5.5
5     6.7
6    True
7   False
8   Kohin
9  Saydad

In [19]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Objcets  10 non-null     object
dtypes: object(1)
memory usage: 212.0+ bytes