In [1]:
import pandas as pd

In [2]:
#dictionary making
d = {
    "Name" : ['Kohin','Saydad','Sehrish','Nahar','Sany','Shanta'],
    "Age" : [22,5,4,48,30,27],
    "Salary" :[50000,40000,30000,20000,10000,5000],
    "Matured" :[True,False,False,True,True,True],
    "Character" : ['Good','Excellent','Excellent','Excellent','Good','Bad']
}

In [3]:
data = pd.DataFrame(d)

In [4]:
data

      Name  Age  Salary  Matured  Character
0    Kohin   22   50000     True       Good
1   Saydad    5   40000    False  Excellent
2  Sehrish    4   30000    False  Excellent
3    Nahar   48   20000     True  Excellent
4     Sany   30   10000     True       Good
5   Shanta   27    5000     True        Bad

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       6 non-null      object
 1   Age        6 non-null      int64
 2   Salary     6 non-null      int64
 3   Matured    6 non-null      bool
 4   Character  6 non-null      object
dtypes: bool(1), int64(2), object(2)
memory usage: 330.0+ bytes

In [6]:
data.dtypes

Name         object
Age           int64
Salary        int64
Matured        bool
Character    object
dtype: object

In [7]:
data['Age']

0    22
1     5
2     4
3    48
4    30
5    27
Name: Age, dtype: int64

In [8]:
data['Age'] = data['Age'].astype('int8')
data['Salary'] = data['Salary'].astype('int32')

In [9]:
data

      Name  Age  Salary  Matured  Character
0    Kohin   22   50000     True       Good
1   Saydad    5   40000    False  Excellent
2  Sehrish    4   30000    False  Excellent
3    Nahar   48   20000     True  Excellent
4     Sany   30   10000     True       Good
5   Shanta   27    5000     True        Bad

In [10]:
data.dtypes

Name         object
Age            int8
Salary        int32
Matured        bool
Character    object
dtype: object

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       6 non-null      object
 1   Age        6 non-null      int8
 2   Salary     6 non-null      int32
 3   Matured    6 non-null      bool
 4   Character  6 non-null      object
dtypes: bool(1), int32(1), int8(1), object(2)
memory usage: 264.0+ bytes

In [12]:
data['Matured'] = data['Matured'].astype('int8')

In [13]:
data

      Name  Age  Salary  Matured  Character
0    Kohin   22   50000        1       Good
1   Saydad    5   40000        0  Excellent
2  Sehrish    4   30000        0  Excellent
3    Nahar   48   20000        1  Excellent
4     Sany   30   10000        1       Good
5   Shanta   27    5000        1        Bad

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       6 non-null      object
 1   Age        6 non-null      int8
 2   Salary     6 non-null      int32
 3   Matured    6 non-null      int8
 4   Character  6 non-null      object
dtypes: int32(1), int8(2), object(2)
memory usage: 264.0+ bytes

In [15]:
data['Salary'] = data['Salary'].astype('float32')

In [16]:
data

      Name  Age   Salary  Matured  Character
0    Kohin   22  50000.0        1       Good
1   Saydad    5  40000.0        0  Excellent
2  Sehrish    4  30000.0        0  Excellent
3    Nahar   48  20000.0        1  Excellent
4     Sany   30  10000.0        1       Good
5   Shanta   27   5000.0        1        Bad

In [17]:
data.dtypes

Name          object
Age             int8
Salary       float32
Matured         int8
Character     object
dtype: object

In [18]:
data['Character'] = data['Character'].map({
    'Bad': 0,
    'Good': 1,
    'Excellent':2
})

In [19]:
data

      Name  Age   Salary  Matured  Character
0    Kohin   22  50000.0        1          1
1   Saydad    5  40000.0        0          2
2  Sehrish    4  30000.0        0          2
3    Nahar   48  20000.0        1          2
4     Sany   30  10000.0        1          1
5   Shanta   27   5000.0        1          0

In [20]:
data.dtypes

Name          object
Age             int8
Salary       float32
Matured         int8
Character      int64
dtype: object

In [21]:
data['Character'] = data['Character'].astype('int8')

In [22]:
data

      Name  Age   Salary  Matured  Character
0    Kohin   22  50000.0        1          1
1   Saydad    5  40000.0        0          2
2  Sehrish    4  30000.0        0          2
3    Nahar   48  20000.0        1          2
4     Sany   30  10000.0        1          1
5   Shanta   27   5000.0        1          0

In [23]:
data.dtypes

Name          object
Age             int8
Salary       float32
Matured         int8
Character       int8
dtype: object